/**
 * Auto-generated contract bindings.
 * 
 * Generated by scripts/generate-bindings.ts
 * 
 * Contract bindings will be generated here when you run:
 *   pnpm build:bindings
 * 
 * This placeholder file allows imports to work before bindings are generated.
 */

// Contract IDs from environment variables
export const MARKET_CONTRACT_ID = process.env.NEXT_PUBLIC_MARKET_CONTRACT_ID ?? '';
export const TREASURY_CONTRACT_ID = process.env.NEXT_PUBLIC_TREASURY_CONTRACT_ID ?? '';
export const OUTCOME_TOKEN_CONTRACT_ID = process.env.NEXT_PUBLIC_OUTCOME_TOKEN_CONTRACT_ID ?? '';
export const RESOLUTION_CONTRACT_ID = process.env.NEXT_PUBLIC_RESOLUTION_CONTRACT_ID ?? '';

// Network configuration
export const NETWORK_PASSPHRASE = 
  process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE ?? 
  'Test SDF Network ; September 2015';

export const SOROBAN_RPC_URL = 
  process.env.NEXT_PUBLIC_SOROBAN_RPC_URL ?? 
  'https://soroban-testnet.stellar.org';

export const HORIZON_URL = 
  process.env.NEXT_PUBLIC_HORIZON_URL ?? 
  'https://horizon-testnet.stellar.org';

// Note: Individual contract exports will be available after running pnpm build:bindings
// export * from './market';
// export * from './treasury';
// export * from './outcome-token';
// export * from './resolution';
