#!/usr/bin/env tsx
/**
 * Generate TypeScript contract bindings from compiled WASM files.
 *
 * This script:
 * 1. Builds all contracts using `stellar contract build`
 * 2. Generates TypeScript client bindings using `stellar contract bindings typescript`
 * 3. Places generated files in apps/web/lib/contracts/
 *
 * Prerequisites:
 * - stellar CLI installed and in PATH
 * - Contract WASM files built (or will build them)
 *
 * Usage:
 *   pnpm build:bindings
 *   or
 *   tsx scripts/generate-bindings.ts
 */

import { execSync } from "child_process";
import { existsSync, mkdirSync, readdirSync, copyFileSync } from "fs";
import { join, basename } from "path";

const ROOT = join(__dirname, "..");
const CONTRACTS_DIR = join(ROOT, "contracts");
const WEB_CONTRACTS_OUTPUT = join(ROOT, "apps", "web", "lib", "contracts");
const WASM_TARGET = join(ROOT, "target", "wasm32v1-none", "release");

interface ContractConfig {
  name: string;
  path: string;
  outputName: string;
}

// Contracts to generate bindings for
const CONTRACTS: ContractConfig[] = [
  {
    name: "market",
    path: join(CONTRACTS_DIR, "market"),
    outputName: "market",
  },
  {
    name: "treasury",
    path: join(CONTRACTS_DIR, "treasury"),
    outputName: "treasury",
  },
  {
    name: "outcome-token",
    path: join(CONTRACTS_DIR, "outcome-token"),
    outputName: "outcome-token",
  },
  {
    name: "resolution",
    path: join(CONTRACTS_DIR, "resolution"),
    outputName: "resolution",
  },
];

function log(message: string) {
  console.log(`[generate-bindings] ${message}`);
}

function error(message: string): never {
  console.error(`[generate-bindings] ERROR: ${message}`);
  process.exit(1);
}

function exec(command: string, cwd?: string): string {
  try {
    return execSync(command, {
      cwd: cwd || ROOT,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
  } catch (err: any) {
    error(`Command failed: ${command}\n${err.stderr || err.message}`);
  }
}

function checkPrerequisites() {
  log("Checking prerequisites...");

  // Check if stellar CLI is installed
  try {
    const version = exec("stellar --version").trim();
    log(`Found stellar CLI: ${version}`);
  } catch {
    error(
      "stellar CLI not found. Install it from https://developers.stellar.org/docs/tools/developer-tools"
    );
  }
}

function buildContracts() {
  log("Building contracts...");

  // Build from root to ensure all workspace contracts are built
  try {
    exec("stellar contract build", ROOT);
    log("✓ Contracts built successfully");
  } catch (err: any) {
    error(`Failed to build contracts: ${err.message}`);
  }

  // Verify WASM files exist
  if (!existsSync(WASM_TARGET)) {
    error(`WASM target directory not found: ${WASM_TARGET}`);
  }

  const wasmFiles = readdirSync(WASM_TARGET).filter((f) => f.endsWith(".wasm"));
  if (wasmFiles.length === 0) {
    error(`No WASM files found in ${WASM_TARGET}`);
  }

  log(`Found ${wasmFiles.length} WASM file(s): ${wasmFiles.join(", ")}`);
}

function generateBindings() {
  log("Generating TypeScript bindings...");

  // Ensure output directory exists
  if (!existsSync(WEB_CONTRACTS_OUTPUT)) {
    mkdirSync(WEB_CONTRACTS_OUTPUT, { recursive: true });
    log(`Created output directory: ${WEB_CONTRACTS_OUTPUT}`);
  }

  for (const contract of CONTRACTS) {
    const wasmFile = join(
      WASM_TARGET,
      `vatix_${contract.name.replace(/-/g, "_")}_contract.wasm`
    );

    if (!existsSync(wasmFile)) {
      log(`⚠ Skipping ${contract.name}: WASM file not found at ${wasmFile}`);
      continue;
    }

    const outputFile = join(
      WEB_CONTRACTS_OUTPUT,
      `${contract.outputName}.ts`
    );

    log(`Generating bindings for ${contract.name}...`);
    log(`  WASM: ${basename(wasmFile)}`);
    log(`  Output: ${outputFile}`);

    try {
      // Generate TypeScript bindings
      const command = `stellar contract bindings typescript --wasm "${wasmFile}" --output-dir "${WEB_CONTRACTS_OUTPUT}" --contract-id ${contract.outputName.toUpperCase()}_CONTRACT --overwrite`;

      exec(command);

      log(`✓ Generated bindings for ${contract.name}`);
    } catch (err: any) {
      log(`⚠ Failed to generate bindings for ${contract.name}: ${err.message}`);
    }
  }
}

function generateIndexFile() {
  log("Generating index.ts...");

  const indexContent = `/**
 * Auto-generated contract bindings.
 * 
 * Generated by scripts/generate-bindings.ts
 * Do not edit this file manually.
 */

// Re-export all contract clients
export * from './market';
export * from './treasury';
export * from './outcome-token';
export * from './resolution';

// Contract IDs from environment variables
export const MARKET_CONTRACT_ID = process.env.NEXT_PUBLIC_MARKET_CONTRACT_ID ?? '';
export const TREASURY_CONTRACT_ID = process.env.NEXT_PUBLIC_TREASURY_CONTRACT_ID ?? '';
export const OUTCOME_TOKEN_CONTRACT_ID = process.env.NEXT_PUBLIC_OUTCOME_TOKEN_CONTRACT_ID ?? '';
export const RESOLUTION_CONTRACT_ID = process.env.NEXT_PUBLIC_RESOLUTION_CONTRACT_ID ?? '';

// Network configuration
export const NETWORK_PASSPHRASE = 
  process.env.NEXT_PUBLIC_NETWORK_PASSPHRASE ?? 
  'Test SDF Network ; September 2015';

export const SOROBAN_RPC_URL = 
  process.env.NEXT_PUBLIC_SOROBAN_RPC_URL ?? 
  'https://soroban-testnet.stellar.org';

export const HORIZON_URL = 
  process.env.NEXT_PUBLIC_HORIZON_URL ?? 
  'https://horizon-testnet.stellar.org';
`;

  const indexPath = join(WEB_CONTRACTS_OUTPUT, "index.ts");
  require("fs").writeFileSync(indexPath, indexContent, "utf-8");
  log(`✓ Generated ${indexPath}`);
}

function main() {
  log("Starting TypeScript bindings generation...\n");

  checkPrerequisites();
  buildContracts();
  generateBindings();
  generateIndexFile();

  log("\n✓ TypeScript bindings generated successfully!");
  log(`Output directory: ${WEB_CONTRACTS_OUTPUT}`);
  log("\nNext steps:");
  log("  1. Update .env.local with your contract IDs");
  log("  2. Use the generated clients in your components");
  log("  3. Run 'pnpm dev' to test the integration");
}

// Run if executed directly
if (require.main === module) {
  main();
}
